name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Grant the minimum required permissions
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Week 3)
        working-directory: WEEK-3
        run: npm ci

      - name: Build (TypeScript -> dist)
        working-directory: WEEK-3
        run: npm run build

      - name: "Optional: Install & Build Week 4 (if present)"
        if: ${{ hashFiles('WEEK-4/package.json') != '' }}
        working-directory: WEEK-4
        shell: bash
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          npm run build

      - name: Stage multi-week site
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          rm -rf site
          mkdir -p site
          # Copy static weeks if present
          if [ -d "WEEK-1" ]; then cp -r WEEK-1 site/WEEK-1; fi
          if [ -d "WEEK-2" ]; then cp -r WEEK-2 site/WEEK-2; fi
          # Stage Week 3: prefer root HTML/CSS + compiled JS from dist
          mkdir -p site/WEEK-3
          # Copy HTML (prefer dist if present, else root)
          if [ -f "WEEK-3/dist/index.html" ]; then cp WEEK-3/dist/index.html site/WEEK-3/; elif [ -f "WEEK-3/index.html" ]; then cp WEEK-3/index.html site/WEEK-3/; fi
          # Copy CSS (prefer dist if present, else root)
          if [ -f "WEEK-3/dist/styles.css" ]; then cp WEEK-3/dist/styles.css site/WEEK-3/; elif [ -f "WEEK-3/styles.css" ]; then cp WEEK-3/styles.css site/WEEK-3/; fi
          # Copy favicon if any
          if [ -f "WEEK-3/favicon.ico" ]; then cp WEEK-3/favicon.ico site/WEEK-3/; elif [ -f "WEEK-3/dist/favicon.ico" ]; then cp WEEK-3/dist/favicon.ico site/WEEK-3/; fi
          # Copy compiled JS always
          if compgen -G "WEEK-3/dist/*.js" > /dev/null; then cp WEEK-3/dist/*.js site/WEEK-3/; fi
          # Copy Week 4 build output (support Vite dist/ or CRA build/)
          if [ -d "WEEK-4/dist" ]; then mkdir -p site/WEEK-4 && cp -r WEEK-4/dist/* site/WEEK-4/; fi
          if [ -d "WEEK-4/build" ]; then mkdir -p site/WEEK-4 && cp -r WEEK-4/build/* site/WEEK-4/; fi
          # Generate root index.html with links to weeks
          cat > site/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>WEBZENITH Bootcamp – Weeks</title>
            <meta name="color-scheme" content="light dark" />
            <style>
              body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', Arial, sans-serif; margin: 2rem; line-height: 1.6; }
              h1 { margin-bottom: 1rem; }
              ul { padding-left: 1.2rem; }
              a { color: #2563eb; text-decoration: none; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>WEBZENITH Bootcamp</h1>
            <p>Select a week:</p>
            <ul>
          EOF
          for d in site/WEEK-*; do
            if [ -d "$d" ]; then
              name=$(basename "$d")
              echo "              <li><a href=\"./$name/\">$name</a></li>" >> site/index.html
            fi
          done
          cat >> site/index.html << 'EOF'
            </ul>
          </body>
          </html>
          EOF

      - name: List staged site contents (debug)
        shell: bash
        run: |
          echo "Staged site structure:"
          ls -la site || true
          echo "Top-level week folders:"
          ls -la site | sed -n '1,200p' || true
          echo "Files under WEEK-3:" && (ls -la site/WEEK-3 || true)

      - name: "Guard: ensure Week 3 index exists"
        shell: bash
        run: |
          if [ ! -f "site/WEEK-3/index.html" ]; then
            echo "ERROR: site/WEEK-3/index.html not found. Ensure WEEK-3/index.html exists or dist includes it." >&2
            exit 1
          fi

      - name: "Guard: ensure Week 3 script exists"
        shell: bash
        run: |
          if ! compgen -G "site/WEEK-3/*.js" > /dev/null; then
            echo "ERROR: No JS found under site/WEEK-3. Ensure tsc outputs dist/*.js and staging copies it." >&2
            exit 1
          fi

      - name: Upload site as debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-debug
          path: site
          retention-days: 3

      - name: Upload Pages artifact (multi-week site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
